import Chip from './chip.js'
import { defaults } from '../../globals.js'

export default class Fonzo extends Chip {

  constructor (main) {
    super(main)

    this.init('fonzo', ['count', 'width', 'height'])

    this.reset()
  }

  reset () {
    super.reset()

    this.memory.from_array(this._top + 33 * this._cell_size, [
      [
        '      ',
        '   w  ',
        '   w  ',
        '   w  ',
        '      ',
        '   w  ',
        '      ',
      ],
      [
        '      ',
        '  w w ',
        '  w w ',
        '      ',
        '      ',
        '      ',
        '      ',
      ],
      [
        '      ',
        '  ww  ',
        ' wwww ',
        '  ww  ',
        ' wwww ',
        '  ww  ',
        '      ',
      ],
      [
        '      ',
        '  www ',
        ' www  ',
        '  w w ',
        ' www  ',
        '  w   ',
        '      ',
      ],
      [
        '      ',
        ' w  w ',
        '   w  ',
        '  w   ',
        ' w  w ',
        '      ',
        '      ',
      ],
      [
        '      ',
        '  w   ',
        ' w w  ',
        ' www w',
        ' w  w ',
        '  ww w',
        '      ',
      ],
      [
        '      ',
        '  w   ',
        '  w   ',
        '      ',
        '      ',
        '      ',
        '      ',
      ],
      [
        '      ',
        '   w  ',
        '  w   ',
        '  w   ',
        '  w   ',
        '   w  ',
        '      ',
      ],
      [
        '      ',
        '  w   ',
        '   w  ',
        '   w  ',
        '   w  ',
        '  w   ',
        '      ',
      ],
      [
        '      ',
        ' w w  ',
        '  w   ',
        ' www  ',
        '  w   ',
        ' w w  ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '  w   ',
        ' www  ',
        '  w   ',
        '      ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '      ',
        '      ',
        '  w   ',
        ' w    ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '      ',
        ' www  ',
        '      ',
        '      ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '      ',
        '      ',
        '      ',
        '  w   ',
        '      ',
      ],
      [
        '      ',
        '    w ',
        '   w  ',
        '  w   ',
        ' w    ',
        '      ',
        '      ',
      ],
      [
        '      ',
        ' wwww ',
        ' w  w ',
        ' w  w ',
        ' w  w ',
        ' wwww ',
        '      ',
      ],
      [
        '      ',
        '   w  ',
        '  ww  ',
        '   w  ',
        '   w  ',
        '   w  ',
        '      ',
      ],
      [
        '      ',
        ' www  ',
        '    w ',
        '  ww  ',
        ' w    ',
        ' wwww ',
        '      ',
      ],
      [
        '      ',
        ' www  ',
        '    w ',
        '  ww  ',
        '    w ',
        ' www  ',
        '      ',
      ],
      [
        '      ',
        ' w  w ',
        ' w  w ',
        ' wwww ',
        '    w ',
        '    w ',
        '      ',
      ],
      [
        '      ',
        ' wwww ',
        ' w    ',
        ' www  ',
        '    w ',
        ' www  ',
        '      ',
      ],
      [
        '      ',
        '  www ',
        ' w    ',
        ' www  ',
        ' w  w ',
        '  ww  ',
        '      ',
      ],
      [
        '      ',
        ' wwww ',
        '    w ',
        '   w  ',
        '   w  ',
        '  w   ',
        '      ',
      ],
      [
        '      ',
        '  ww  ',
        ' w  w ',
        '  ww  ',
        ' w  w ',
        '  ww  ',
        '      ',
      ],
      [
        '      ',
        ' wwww ',
        ' w  w ',
        ' wwww ',
        '    w ',
        ' wwww ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '  w   ',
        '      ',
        '  w   ',
        '      ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '  w   ',
        '      ',
        '  w   ',
        ' w    ',
        '      ',
      ],
      [
        '      ',
        '   w  ',
        '  w   ',
        ' w    ',
        '  w   ',
        '   w  ',
        '      ',
      ],
      [
        '      ',
        '      ',
        ' www  ',
        '      ',
        ' www  ',
        '      ',
        '      ',
      ],
      [
        '      ',
        ' w    ',
        '  w   ',
        '   w  ',
        '  w   ',
        ' w    ',
        '      ',
      ],
      [
        '      ',
        ' ww   ',
        '   w  ',
        '  w   ',
        '      ',
        '  w   ',
        '      ',
      ],
      [
        '      ',
        '  ww  ',
        ' w ww ',
        ' w ww ',
        ' w    ',
        '  www ',
        '      ',
      ],
      [
        '      ',
        '  ww  ',
        ' w  w ',
        ' wwww ',
        ' w  w ',
        ' w  w ',
        '      ',
      ],
      [
        '      ',
        ' www  ',
        ' w  w ',
        ' www  ',
        ' w  w ',
        ' www  ',
        '      ',
      ],
      [
        '      ',
        '  www ',
        ' w    ',
        ' w    ',
        ' w    ',
        '  www ',
        '      ',
      ],
      [
        '      ',
        ' www  ',
        ' w  w ',
        ' w  w ',
        ' w  w ',
        ' www  ',
        '      ',
      ],
      [
        '      ',
        ' wwww ',
        ' w    ',
        ' www  ',
        ' w    ',
        ' wwww ',
        '      ',
      ],
      [
        '      ',
        ' wwww ',
        ' w    ',
        ' www  ',
        ' w    ',
        ' w    ',
        '      ',
      ],
      [
        '      ',
        '  ww  ',
        ' w  w ',
        ' w    ',
        ' w ww ',
        '  ww  ',
        '      ',
      ],
      [
        '      ',
        ' w  w ',
        ' w  w ',
        ' wwww ',
        ' w  w ',
        ' w  w ',
        '      ',
      ],
      [
        '      ',
        ' www  ',
        '  w   ',
        '  w   ',
        '  w   ',
        ' www  ',
        '      ',
      ],
      [
        '      ',
        '  www ',
        '   w  ',
        '   w  ',
        ' w w  ',
        '  w   ',
        '      ',
      ],
      [
        '      ',
        ' w  w ',
        ' w w  ',
        ' ww   ',
        ' w w  ',
        ' w  w ',
        '      ',
      ],
      [
        '      ',
        ' w    ',
        ' w    ',
        ' w    ',
        ' w    ',
        ' wwww ',
        '      ',
      ],
      [
        '      ',
        ' w   w',
        ' wwwww',
        ' w w w',
        ' w   w',
        ' w   w',
        '      ',
      ],
      [
        '      ',
        ' w   w',
        ' ww  w',
        ' w w w',
        ' w  ww',
        ' w   w',
        '      ',
      ],
      [
        '      ',
        '  ww  ',
        ' w  w ',
        ' w  w ',
        ' w  w ',
        '  ww  ',
        '      ',
      ],
      [
        '      ',
        ' www  ',
        ' w  w ',
        ' www  ',
        ' w    ',
        ' w    ',
        '      ',
      ],
      [
        '      ',
        '  ww  ',
        ' w  w ',
        ' w  w ',
        ' w  w ',
        '  ww  ',
        '   w  ',
      ],
      [
        '      ',
        ' www  ',
        ' w  w ',
        ' www  ',
        ' w  w ',
        ' w  w ',
        '      ',
      ],
      [
        '      ',
        '  www ',
        ' w    ',
        '  ww  ',
        '    w ',
        ' www  ',
        '      ',
      ],
      [
        '      ',
        ' wwwww',
        '   w  ',
        '   w  ',
        '   w  ',
        '   w  ',
        '      ',
      ],
      [
        '      ',
        ' w  w ',
        ' w  w ',
        ' w  w ',
        ' w  w ',
        '  ww  ',
        '      ',
      ],
      [
        '      ',
        ' w   w',
        ' w   w',
        ' w   w',
        '  w w ',
        '   w  ',
        '      ',
      ],
      [
        '      ',
        ' w   w',
        ' w   w',
        ' w   w',
        ' w w w',
        ' ww ww',
        '      ',
      ],
      [
        '      ',
        ' w   w',
        '  w w ',
        '   w  ',
        '  w w ',
        ' w   w',
        '      ',
      ],
      [
        '      ',
        ' w   w',
        '  w w ',
        '   w  ',
        '   w  ',
        '   w  ',
        '      ',
      ],
      [
        '      ',
        ' wwww ',
        '    w ',
        '  ww  ',
        ' w    ',
        ' wwww ',
        '      ',
      ],
      [
        '      ',
        ' www  ',
        ' w    ',
        ' w    ',
        ' w    ',
        ' www  ',
        '      ',
      ],
      [
        '      ',
        ' w    ',
        '  w   ',
        '   w  ',
        '    w ',
        '      ',
        '      ',
      ],
      [
        '      ',
        '  www ',
        '    w ',
        '    w ',
        '    w ',
        '  www ',
        '      ',
      ],
      [
        '      ',
        '  w   ',
        ' w w  ',
        '      ',
        '      ',
        '      ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '      ',
        '      ',
        '      ',
        ' wwww ',
        '      ',
      ],
      [
        '      ',
        '  w   ',
        '   w  ',
        '      ',
        '      ',
        '      ',
        '      ',
      ],
      [
        '      ',
        '  ww  ',
        '    w ',
        '  www ',
        ' w  w ',
        '  ww  ',
        '      ',
      ],
      [
        '      ',
        ' w    ',
        ' www  ',
        ' w  w ',
        ' w  w ',
        ' www  ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '  www ',
        ' w    ',
        ' w    ',
        '  www ',
        '      ',
      ],
      [
        '      ',
        '    w ',
        '  www ',
        ' w  w ',
        ' w  w ',
        '  www ',
        '      ',
      ],
      [
        '      ',
        '  ww  ',
        ' w  w ',
        ' wwww ',
        ' w    ',
        '  www ',
        '      ',
      ],
      [
        '      ',
        '  ww  ',
        ' w  w ',
        'www   ',
        ' w    ',
        ' w    ',
        '      ',
      ],
      [
        '      ',
        '  ww  ',
        ' w  w ',
        '  www ',
        '    w ',
        ' www  ',
        '      ',
      ],
      [
        '      ',
        ' w    ',
        ' w    ',
        ' www  ',
        ' w  w ',
        ' w  w ',
        '      ',
      ],
      [
        '      ',
        '  w   ',
        '      ',
        '  w   ',
        '  w   ',
        '  w   ',
        '      ',
      ],
      [
        '      ',
        '    w ',
        '      ',
        '    w ',
        ' w  w ',
        '  ww  ',
        '      ',
      ],
      [
        '      ',
        '    w ',
        ' w w  ',
        ' ww   ',
        ' w w  ',
        ' w  w ',
        '      ',
      ],
      [
        '      ',
        '   w  ',
        '   w  ',
        '   w  ',
        '   w  ',
        '   w  ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '  w w ',
        ' w w w',
        ' w   w',
        ' w   w',
        '      ',
      ],
      [
        '      ',
        '      ',
        ' www  ',
        ' w  w ',
        ' w  w ',
        ' w  w ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '  ww  ',
        ' w  w ',
        ' w  w ',
        '  ww  ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '  ww  ',
        ' w  w ',
        ' www  ',
        ' w    ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '  ww  ',
        ' w  w ',
        '  www ',
        '    w ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '  ww  ',
        ' w  w ',
        ' w    ',
        ' w    ',
        '      ',
      ],
      [
        '      ',
        '  ww  ',
        ' w    ',
        '  w   ',
        '   w  ',
        ' ww   ',
        '      ',
      ],
      [
        '      ',
        '  w   ',
        ' www  ',
        '  w   ',
        '  w w ',
        '   w  ',
        '      ',
      ],
      [
        '      ',
        '      ',
        ' w  w ',
        ' w  w ',
        ' w  w ',
        '  ww  ',
        '      ',
      ],
      [
        '      ',
        '      ',
        ' w  w ',
        ' w w  ',
        ' ww   ',
        ' w    ',
        '      ',
      ],
      [
        '      ',
        '      ',
        ' w   w',
        ' w   w',
        ' w w w',
        '  w w ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '  w w ',
        '   w  ',
        '   w  ',
        '  w w ',
        '      ',
      ],
      [
        '      ',
        '      ',
        ' w  w ',
        '  www ',
        '    w ',
        ' www  ',
        '      ',
      ],
      [
        '      ',
        '      ',
        ' wwww ',
        '   w  ',
        '  w   ',
        ' wwww ',
        '      ',
      ],
      [
        '      ',
        '   ww ',
        '  w   ',
        ' ww   ',
        '  w   ',
        '   ww ',
        '      ',
      ],
      [
        '      ',
        '  w   ',
        '  w   ',
        '  w   ',
        '  w   ',
        '  w   ',
        '      ',
      ],
      [
        '      ',
        ' ww   ',
        '   w  ',
        '   ww ',
        '   w  ',
        ' ww   ',
        '      ',
      ],
      [
        '      ',
        '      ',
        '    w ',
        '  ww  ',
        ' w    ',
        '      ',
        '      ',
      ],
    ], defaults.chars_map)

    this.test()
  }

  draw (x, y, c, fg, bg) {
    return this.guideo.blit(this._top + c * this._cell_size, x, y, this._width, this._height, fg, bg)
  }

  test () {
    // this.draw(40, 40, 65, 10, 3)
    // this.draw(47, 40, 66, 12, 15)
    // this.draw(54, 40, 33, 5, 8)

    let cw = this._width
    let ch = this._height

    let xx = 0
    let y = 4 * ch
    for (let x = 33; x < 73; x++) {
      this.draw(xx * cw, y, x, _.random(2, 15))
      xx++
    }

    xx = 0
    y = 5 * ch
    for (let x = 73; x < 113; x++) {
      this.draw(xx * cw, y, x, _.random(2, 15))
      xx++
    }

    xx = 0
    y = 6 * ch
    for (let x = 113; x < 126; x++) {
      this.draw(xx * cw, y, x, _.random(2, 15))
      xx++
    }

    this.draw(10 * cw, 10 * ch, 'A'.charCodeAt(0))
    this.draw(11 * cw, 10 * ch, 'l'.charCodeAt(0))
    this.draw(12 * cw, 10 * ch, 'a'.charCodeAt(0))
    this.draw(13 * cw, 10 * ch, 'i'.charCodeAt(0))
    this.draw(14 * cw, 10 * ch, 'n'.charCodeAt(0))
  }

}
